### PR TITLE
Docker update v2.0.0 - generate genepanels and manifest

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Add environment variables needed in Docker
- Functional genepanels and manifest generation
- Get latest version of clinical indication for manifest generation

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57)

### CODE REVIEW

**Comment by mattgarner** [comment]
Also adding @jethror1 as a reviewer, since we're trying to move this into the infrastructure team

**Review by jethror1 — CHANGES_REQUESTED** [review]
Need to update readme with docker things and can you add an example config file to the repo

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-:-MqEYjwV4Dqmd6YnBeE0:bu3wolm)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/utils.py, line 1246 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXFc2CxocaNyLdSD7:-MqEXFc2CxocaNyLdSD8:btokun) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1246)):*
> ```Python
>                         continue
> 
>                     # remove TRAC and IGHM genes from genepanels and manifest
> ```

why are we doing this? should this be hardcoded in?
___
*[ops/utils.py, line 1308 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXQ9NEcLLytnjk91Y:-MqEXQ9NEcLLytnjk91Z:b9h4v8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1308)):*
> ```Python
> 
> 
> def get_latest_clinical_indication_data(query_result):
> ```

docstring
___
*[ops/utils.py, line 1325 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXtEv9gAPw_l-MGuG:-MqEXtEv9gAPw_l-MGuH:b-bddfpe) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1325)):*
> ```Python
> 
>             # if new date is higher replace all stored dates
>             if dated_version > dated_stored_version:
> ```

what if date isn't greater? do we care / should we know? when would this happen?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[ops/utils.py, line 1246 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXFc2CxocaNyLdSD7:-MqF3YTVCTZu53B94hSf:b4z37tc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1246)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why are we doing this? should this be hardcoded in?
</blockquote></details>

These are mitochondrial genes which are not covered by Nirvana so we need to remove them. It's not an elegant solution but that way the database stores everything while our reports can still function.
___
*[ops/utils.py, line 1325 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXtEv9gAPw_l-MGuG:-MqF5Bqt-2_SpMvEqtUh:b-6dlpu3) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1325)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what if date isn't greater? do we care / should we know? when would this happen?
</blockquote></details>

if the date in "lower", we don't care. We want the most up to date info in the manifest so:
- greater date: remove the stored clinical indication(s), and store the most recent one
- equal date: it is possible that 2 panels can be linked to the same clinical indication and be at the same date, so retain the stored one and add the one that we are looping on
- lesser date: it is possible but we don't care, we want to output the most recent clinical indication(s)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[ops/utils.py, line 1308 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXQ9NEcLLytnjk91Y:-MqFTKCq1Xh6kRQiHaUd:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1308)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/utils.py, line 1246 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXFc2CxocaNyLdSD7:-MqFh5va0nd5D8IwxU-_:b-jxo1fx) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1246)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

These are mitochondrial genes which are not covered by Nirvana so we need to remove them. It's not an elegant solution but that way the database stores everything while our reports can still function.
</blockquote></details>

that's fair, makes sense

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[ops/utils.py, line 1246 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-MqEXFc2CxocaNyLdSD7:-MqJJBI47tkCD5JkPQDR:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/bfc9baa8d69e109a62ab88d1c716d09533e505d0/ops/utils.py#L1246)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

that's fair, makes sense
</blockquote></details>

Done.

**Comment by jethror1** [comment]
this @Yu-jinKim 

> Need to update readme with docker things and can you add an example config file to the repo
> 
> > _[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-:-MqEYjwV4Dqmd6YnBeE0:bu3wolm)_ status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)
>

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/57#-:-N-7ltNy2I4DBZib1rde:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
