### PR TITLE
v1.0.0 - check

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- check gene --> function to check the transcript assigned to the given gene
- check_panelapp_dump_against_db --> check content of database given a panelapp dump folder
- check_tests --> check tests and their links given a National directory xls

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/8)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/8)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/check.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTFujJDfYjfbuFIAey:-MNTFujKAzDGrcKMlhbh:b4y79o9) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L1)):*
> ```Python
> from .logger import setup_logging
> ```

script docstring would be nice, explain each function checks
___
*[ops/check.py, line 66 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTaACVAtIA5ubLsjWo:-MNTaACVAtIA5ubLsjWp:b-8911ms) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L66)):*
> ```Python
> 
>     # Get the ids for the references for use with strs and cnvs
>     grch37_id = session.query(ref_tb.c.id).filter(
> ```

do you handle if you end up with more than one entry for 37/38 and if ids for same are split in other tables?
___
*[ops/check.py, line 91 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTaZZM8zJ4RcLDBy3d:-MNTaZZM8zJ4RcLDBy3e:bj6t9me) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L91)):*
> ```Python
> 
>     else:
>         LOGGER.error("Expected nb of superpanels is incorrect")
> ```

maybe add a diff here and log the panel mismatch, would make debugging easier
___
*[ops/check.py, line 140 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTarzNAIbexm9enWxj:-MNTarzNAIbexm9enWxk:bus21io) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L140)):*
> ```Python
>             return
>     else:
>         LOGGER.error("Expected nb of panels is incorrect")
> ```

again add diff for logs of panel mismatch
___
*[ops/check.py, line 140 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTbiq15KqQMyo1dlu8:-MNTbiq15KqQMyo1dlu9:b-yyezog) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L140)):*
> ```Python
>             return
>     else:
>         LOGGER.error("Expected nb of panels is incorrect")
> ```

also put number instead of nb in a message
___
*[ops/check.py, line 182 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTbAYiAJKC7UuhKQzw:-MNTbAYiAJKC7UuhKQzx:bp28y8p) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L182)):*
> ```Python
>                 # Get all transcripts for gene
>                 refseq_values = [
>                     tx.split(".")[0]
> ```

why splitting on '.'? is this to remove transcript versions, if so why?
___
*[ops/check.py, line 242 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTbsMR9OwYaPpQcM5S:-MNTbsMR9OwYaPpQcM5T:bvtxny1) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L242)):*
> ```Python
>                     if len(db_regions) != len(exon_data):
>                         msg = (
>                             f"{panel_name} - {symbol} - {tx}: Nb of regions "
> ```

Number not nb in message
___
*[ops/check.py, line 299 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTc6tG28kmKffxrMtq:-MNTc6tG28kmKffxrMtr:b-yos6mr) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L299)):*
> ```Python
>                     msg = (
>                         f"{panel_name} - {name}: Data for the str is not correct"
>                     )
> ```

could this all be added to one msg then one call to logger?
___
*[ops/check.py, line 336 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNT_DzU144afQbOf9rL:-MNT_DzU144afQbOf9rM:bg5ifa9) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L336)):*
> ```Python
>                             )
>                             LOGGER.error(msg)
> ```

is there a chance of ref not being 37 or 38 (i.e null) and needs handling
___
*[ops/check.py, line 409 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTIw5Q6wQF2NGgENan:-MNTIw5Q6wQF2NGgENao:bfvwo9o) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L409)):*
> ```Python
>     # Check if the number of imported tests is the same as the number of tests in the xls
>     if len(test2target) != len(db_tests):
>         print("Tests are bad")
> ```

more helpful message plus logging
___
*[ops/check.py, line 418 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTZ5pu5GPIC2-3VwPk:-MNTZ5pu5GPIC2-3VwPl:b-wiokcw) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L418)):*
> ```Python
>         panel_targets = test2target[test_id]["panels"]
> 
>         # If the test has panels associated to it
> ```

why would a test not have panels?\
___
*[ops/check.py, line 433 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTYzCvA3N5yCQPsitk:-MNTYzCvA3N5yCQPsitl:b1i5z9q) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L433)):*
> ```Python
> 
>                 if str(panelapp_id) not in test2target[test_id]["panels"]:
>                     print("Panel is bad")
> ```

more helpful message, logging
___
*[ops/check.py, line 456 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTcWjUEktbEieIma4V:-MNTcWjUEktbEieIma4W:b-l6dnp8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L456)):*
> ```Python
> 
>                 if symbol not in test2target[test_id]["genes"]:
>                     print("Gene is bad")
> ```

not the most helpful message, maybe say that where the gene symbol is missing from

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/8)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/check.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTFujJDfYjfbuFIAey:-MNcP7rFEFupua7KZku3:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

script docstring would be nice, explain each function checks
</blockquote></details>

Done.
___
*[ops/check.py, line 66 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTaACVAtIA5ubLsjWo:-MNcPI461Ke2P428ZLkA:b-hree71) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L66)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you handle if you end up with more than one entry for 37/38 and if ids for same are split in other tables?
</blockquote></details>

there's only 2 entries in that table, GRCh37 and GRCh38
___
*[ops/check.py, line 182 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTbAYiAJKC7UuhKQzw:-MNcPWg67XauSxvwYrVU:b-y1h5oi) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L182)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why splitting on '.'? is this to remove transcript versions, if so why?
</blockquote></details>

transcripts version can change so I'm storing transcript name and version separated
___
*[ops/check.py, line 336 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNT_DzU144afQbOf9rL:-MNcPzw90MJuuvOcO0y_:b-99tx5r) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L336)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is there a chance of ref not being 37 or 38 (i.e null) and needs handling
</blockquote></details>

ref was added manually so no
___
*[ops/check.py, line 409 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTIw5Q6wQF2NGgENan:-MNcQ4gkDhMFxP6AUASq:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L409)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

more helpful message plus logging
</blockquote></details>

Done.
___
*[ops/check.py, line 418 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTZ5pu5GPIC2-3VwPk:-MNcQ6OX1fDw2lEM_0qZ:b-rotn8a) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L418)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why would a test not have panels?\
</blockquote></details>

test can have single genes, panels or both
___
*[ops/check.py, line 433 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTYzCvA3N5yCQPsitk:-MNcQApd-tEWzk67AEsx:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L433)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

more helpful message, logging
</blockquote></details>

Done.
___
*[ops/check.py, line 456 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTcWjUEktbEieIma4V:-MNcQBnX7h3n6VHdhtCF:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L456)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not the most helpful message, maybe say that where the gene symbol is missing from
</blockquote></details>

Done.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/8)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1)

___
*[ops/check.py, line 91 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTaZZM8zJ4RcLDBy3d:-MNxbetH479rFYkRPpkc:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L91)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

maybe add a diff here and log the panel mismatch, would make debugging easier
</blockquote></details>

Done.
___
*[ops/check.py, line 140 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTarzNAIbexm9enWxj:-MNxbfDC1DtfEz2m5zd_:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L140)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

again add diff for logs of panel mismatch
</blockquote></details>

Done.
___
*[ops/check.py, line 140 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTbiq15KqQMyo1dlu8:-MNxcYVQ-he85k6BLLB7:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L140)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

also put number instead of nb in a message
</blockquote></details>

Done.
___
*[ops/check.py, line 242 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTbsMR9OwYaPpQcM5S:-MNxcUj9Bdv_gjA18Zxd:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L242)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Number not nb in message
</blockquote></details>

Done.
___
*[ops/check.py, line 299 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MNTc6tG28kmKffxrMtq:-MNxcVCbC5b4v5x8pvZP:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ada36986f29cf8fce472c64904bc0ad0ecbb1cc2/ops/check.py#L299)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could this all be added to one msg then one call to logger?
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/8)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[ops/check.py, line 35 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MO10Hsz1x1_tpIyEo88:-MO10Hsz1x1_tpIyEo89:b-ibdaqe) ([raw file](https://github.com/eastgenomics/panel_ops/blob/b3e7029710f4721b1ed621c3a0305e6fcf9f4e94/ops/check.py#L35)):*
> ```Python
>                 print(f"Exon_nb: {exon_nb}\t{chrom}\t{start}-{end}")
>     else:
>         print(f"No transcript for {gene}")
> ```

does this need logging?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/8)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[ops/check.py, line 35 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/8#-MO10Hsz1x1_tpIyEo88:-MO13x46-kV5Dfqf9O5M:b-bcm5st) ([raw file](https://github.com/eastgenomics/panel_ops/blob/b3e7029710f4721b1ed621c3a0305e6fcf9f4e94/ops/check.py#L35)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this need logging?
</blockquote></details>

I don't think so, this is not really checking the database but it's more something like panel_prep nirvana_transcripts

**Pull request closed without merging**
