### PR TITLE
v1.0.0 - queries

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- find gemini name using part of it: I can see us being given just the R code for a reanalysis or something
- find genes with gemini name

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/9)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/9)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/queries.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTBLueB4WprLWoLotP:-MNTBLuf2-IOF7PxcHjg:bedpy3b) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L2)):*
> ```Python
> def get_gemini_name(session, meta, part_of_gemini_name: str):
>     """ Return the gemini name using part of this name
> ```

this name?
___
*[ops/queries.py, line 17 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTC6Ca9IRVJvL0wIQa:-MNTC6Ca9IRVJvL0wIQb:b-o67hsl) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L17)):*
> ```Python
>     test_name = session.query(test_tb.c.gemini_name).filter(
>         test_tb.c.gemini_name.like(f"%{part_of_gemini_name}%")
>     ).one()[0]
> ```

is there chance of returning more than 1, and would you always want the first?
___
*[ops/queries.py, line 19 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTCC445HMH_cQkh2eg:-MNTCC445HMH_cQkh2eh:b7r8g7l) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L19)):*
> ```Python
>     ).one()[0]
> 
>     print(test_name)
> ```

keeping prints?
___
*[ops/queries.py, line 43 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTEPG790VzwoqW9k8w:-MNTEPG790VzwoqW9k8x:b4w16vx) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L43)):*
> ```Python
> 
>     test_id = session.query(test_tb.c.id).filter(
>         test_tb.c.gemini_name.like(f"%{gemini_name}%")
> ```

is there any where the name is a subset of a larger name, and this would return both?
___
*[ops/queries.py, line 68 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTEy3T2HhdtqZ1MgIa:-MNTEy3T2HhdtqZ1MgIb:biebaqw) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L68)):*
> ```Python
>     genes = genes_from_tests + genes_from_panels
> 
>     print(",".join([f"_{gene[0]}" for gene in genes]))
> ```

whats the _ for / comment what this is for

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/9)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/queries.py, line 66 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTFCecEG5SSLSvUEGl:-MNTFCecEG5SSLSvUEGm:b-ix6xsj) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L66)):*
> ```Python
>     ).all()
> 
>     genes = genes_from_tests + genes_from_panels
> ```

maybe explain structure of this in a comment, is this a list of lists / tuples etc?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/9)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[ops/queries.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTBLueB4WprLWoLotP:-MNZ55UUApMp5eHvr_88:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this name?
</blockquote></details>

Done.
___
*[ops/queries.py, line 17 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTC6Ca9IRVJvL0wIQa:-MNZ56BCEohbm8MVHMMf:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L17)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is there chance of returning more than 1, and would you always want the first?
</blockquote></details>

Done.
___
*[ops/queries.py, line 19 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTCC445HMH_cQkh2eg:-MNZ56s45Gip4lY4Iwbx:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

keeping prints?
</blockquote></details>

Done.
___
*[ops/queries.py, line 43 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTEPG790VzwoqW9k8w:-MNZ58Ok6Kr_gdsdiOvD:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L43)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is there any where the name is a subset of a larger name, and this would return both?
</blockquote></details>

Done.
___
*[ops/queries.py, line 66 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTFCecEG5SSLSvUEGl:-MNZ59YBEHiGhCG45fV2:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L66)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

maybe explain structure of this in a comment, is this a list of lists / tuples etc?
</blockquote></details>

Done.
___
*[ops/queries.py, line 68 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/9#-MNTEy3T2HhdtqZ1MgIa:-MNZ5BgyCW_xgnGZguU1:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/56c373fb3ce5cb783f9bad78270f65c8e0ffe175/ops/queries.py#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whats the _ for / comment what this is for
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
