### PR TITLE
V1.0.0 generate

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/generate.py, line 99 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6LIMFEpRzFg9HyH9z:-MT6LIMFEpRzFg9HyHA-:b32x0h) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L99)):*
> ```Python
>     for panel_row in session.query(panel_tb):
>         panel_id, panelapp_id, name, panel_type = panel_row
> ```

ws
___
*[ops/generate.py, line 173 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NMfi0nLQXgcOrrqM:-MT6NMfi0nLQXgcOrrqN:b-lkk9vs) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L173)):*
> ```Python
>     output_folder = f"sql_dump/{get_date()}-{output_index}_gms_panels"
> 
>     # don't want to overwrite files so create folders using the output index
> ```

you use this a few times but not sure on a nice way since they're different strings
___
*[ops/generate.py, line 218 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NhnG5E8YW-EipTJC:-MT6NhnG5E8YW-EipTJD:b2ni0j2) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L218)):*
> ```Python
>     """
> 
>     msg = "Gathering data from panelapp dump and co"
> ```

co?
___
*[ops/generate.py, line 289 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NxHS5fx86nQN1082:-MT6NxHS5fx86nQN1083:b-6fu2d2) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L289)):*
> ```Python
> 
>     output_index = 1
>     output_folder = f"django_fixtures/{get_date()}-{output_index}"
> ```

use today var
___
*[ops/generate.py, line 294 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6Nzpl8FKYHSROKnbI:-MT6Nzpl8FKYHSROKnbJ:bped4kj) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L294)):*
> ```Python
>     while Path(output_folder).is_dir():
>         output_index += 1
>         output_folder = f"django_fixtures/{get_date()}-{output_index}"
> ```

today var
___
*[ops/generate.py, line 304 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6O7Wy7Wl-pKk-PK9h:-MT6O7Wy7Wl-pKk-PK9i:b-7vb0iz) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L304)):*
> ```Python
>         json.dump(all_elements, f, indent=4)
> 
>     # write single json for every table in the db
> ```

you still wanting to dump out to individual files? what benefit for debugging does it have over dumping to one file?
___
*[ops/generate.py, line 397 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6OxVp99xIVnzEnpX6:-MT6OxVp99xIVnzEnpX7:bsyhi6p) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L397)):*
> ```Python
>     output_folder = f"sql_dump/{get_date()}-{output_index}_bio_manifest"
> 
>     # don't want to overwrite files so create folders using the output index
> ```

yeah maybe a function for this that takes the folder name as input would be good, there's 5 of these

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[ops/generate.py, line 173 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NMfi0nLQXgcOrrqM:-MT6TssJDgjuhf-tFUr9:b-bwgc6q) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L173)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you use this a few times but not sure on a nice way since they're different strings
</blockquote></details>

not sure i understand
___
*[ops/generate.py, line 218 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NhnG5E8YW-EipTJC:-MT6U-TH2tvGbNhEOmvD:b-ulfbvy) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L218)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

co?
</blockquote></details>

can remove it
___
*[ops/generate.py, line 289 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NxHS5fx86nQN1082:-MT6U3MC2KLcYoP13EKJ:b-mtzqx) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L289)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

use today var
</blockquote></details>

fair enough
___
*[ops/generate.py, line 294 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6Nzpl8FKYHSROKnbI:-MT6U4l094Hhz7ettluh:b-9roy72) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L294)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

today var
</blockquote></details>

double fair enough
___
*[ops/generate.py, line 304 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6O7Wy7Wl-pKk-PK9h:-MT6U7cU5OIrsLuxvwow:b9h41zd) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L304)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you still wanting to dump out to individual files? what benefit for debugging does it have over dumping to one file?
</blockquote></details>

the full file is 15000 lines long, so even just opening the file can be hard, the individual files help in pinpointing what went wrong in a particular function.
___
*[ops/generate.py, line 397 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6OxVp99xIVnzEnpX6:-MT6UVrZ4z_ZeyYT4KIL:b2nign3) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L397)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

yeah maybe a function for this that takes the folder name as input would be good, there's 5 of these
</blockquote></details>

yep

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/generate.py, line 173 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6NMfi0nLQXgcOrrqM:-MT73fHfERPqAfqUOmDu:b-vxkumc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L173)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not sure i understand
</blockquote></details>

comment was in wrong place and doesn't make sense, ignore it, you've already fixed it
___
*[ops/generate.py, line 304 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6O7Wy7Wl-pKk-PK9h:-MT757NVAy8oRBmvpyc6:b-6pnc84) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L304)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

the full file is 15000 lines long, so even just opening the file can be hard, the individual files help in pinpointing what went wrong in a particular function.
</blockquote></details>

oh that is large, fair enough

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[ops/generate.py, line 99 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MT6LIMFEpRzFg9HyH9z:-MTAZXxO6PeC7KAAWgTq:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d42b0983eb2304fa59ba6d399ba7ff7525b3724a/ops/generate.py#L99)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: all files reviewed, 4 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/generate.py, line 18 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MUTP2ixCOx0bSJgFGof:-MUTP2ixCOx0bSJgFGog:b-u9xqs9) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4c45da2e8de8f126f1228a19a1514d0d666797c7/ops/generate.py#L18)):*
> ```
> _dump
> ```
would _tsvs be more descriptive?
___
*[ops/generate.py, line 26 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MUTPIhX3xs6E14J-ZZM:-MUTPIhX3xs6E14J-ZZN:b-9tdmxz) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4c45da2e8de8f126f1228a19a1514d0d666797c7/ops/generate.py#L26)):*
> ```
> will be
> ```
were
___
*[ops/generate.py, line 125 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MUTWg0K8dgvBBt4jsTl:-MUTWg0L4zcAbs1czwLl:befrpg5) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4c45da2e8de8f126f1228a19a1514d0d666797c7/ops/generate.py#L125)):*
> ```
>     output_folder = get_new_output_folder("sql_dump", "genepanels")
>     Path(output_folder).mkdir(parents=True)
> ```
Calls of the get_new_output_folder() function always seems to be followed by `Path(output_folder).mkdir(parents=True)`
Maybe it would make sense to merge these into a make_new_output_folder function?

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: all files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[ops/generate.py, line 18 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MUTP2ixCOx0bSJgFGof:-MUmmx6X9XKGc1CPkZwL:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4c45da2e8de8f126f1228a19a1514d0d666797c7/ops/generate.py#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> _dump
> ```
would _tsvs be more descriptive?
</blockquote></details>

Done.
___
*[ops/generate.py, line 26 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MUTPIhX3xs6E14J-ZZM:-MUmmxQDEQJ-P9fu1V9d:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4c45da2e8de8f126f1228a19a1514d0d666797c7/ops/generate.py#L26)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> will be
> ```
were
</blockquote></details>

Done.
___
*[ops/generate.py, line 125 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/24#-MUTWg0K8dgvBBt4jsTl:-MUmmxvw7QIneZHtcN9o:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4c45da2e8de8f126f1228a19a1514d0d666797c7/ops/generate.py#L125)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     output_folder = get_new_output_folder("sql_dump", "genepanels")
>     Path(output_folder).mkdir(parents=True)
> ```
Calls of the get_new_output_folder() function always seems to be followed by `Path(output_folder).mkdir(parents=True)`
Maybe it would make sense to merge these into a make_new_output_folder function?
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
