### PR TITLE
V1.0.0 check

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/check.py, line 206 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT6on694NPQEZVvHAqF:-MT6on694NPQEZVvHAqG:b-c1ap4k) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L206)):*
> ```Python
>                     for panel in hd_test_data["panels"]:
>                         # assuming there's not going to be a superpanel for now
>                         features.update(panel_dict[panel]["genes"])
> ```

maybe add a line to check if there is a super panel and log it?
___
*[ops/check.py, line 370 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT7-ouDAaANPDF-pqOZ:-MT7-ouDAaANPDF-pqO_:b32x0h) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L370)):*
> ```Python
>             for subpanel in superpanel_dict[panelapp_id]["subpanels"]:
>                 hgnc_ids.update(panelapp_dict[subpanel]["genes"])
> ```

ws
___
*[ops/check.py, line 375 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT7-qtU3EmTcGxx_Ovc:-MT7-qtU3EmTcGxx_Ovd:b-qusjy1) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L375)):*
> ```Python
>             raise Exception(
>                 f"Panel {panelapp_id} broke through the check. "
>                 "He's too powerful, let him through"
> ```

10 points for good commentary, is this a result of a panel not being in the panelapp dict or superpanel dict? Maybe another pointer message would be good to log to say what check it broke to be verbose
___
*[ops/check.py, line 379 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT70Vq-5pip8NYoRDbA:-MT70Vq-5pip8NYoRDbB:b-ak6soq) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L379)):*
> ```Python
> 
>         # check if the attributes stored are correct
>         if name != panel_data["name"]:
> ```

does this just check the name matches?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[ops/check.py, line 206 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT6on694NPQEZVvHAqF:-MTA_Rwo9MBBhiC1DcbX:bjzymn9) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L206)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

maybe add a line to check if there is a super panel and log it?
</blockquote></details>

since we control what is going to be in the hard coded tests i think it should be fine
___
*[ops/check.py, line 375 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT7-qtU3EmTcGxx_Ovc:-MTA_eRx-wUIigOaNgzu:b-hkuoud) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L375)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

10 points for good commentary, is this a result of a panel not being in the panelapp dict or superpanel dict? Maybe another pointer message would be good to log to say what check it broke to be verbose
</blockquote></details>

yes, this shouldn't happen all panels should either be in panelapp dict or superpanel dict
___
*[ops/check.py, line 379 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT70Vq-5pip8NYoRDbA:-MTA_rByBQj6rtl2Skv4:by1ir18) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L379)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this just check the name matches?
</blockquote></details>

check the name of the panel in the database and the name gathered in the data dump are equal, yes

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: all files reviewed, 7 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/check.py, line 15 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdGZeo9JroCzkR67iP:-MUdGZeo9JroCzkR67iQ:b-oblh6o) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L15)):*
> ```
> ci2targets
> ```
Are the targets the panels associated with each indication?
___
*[ops/check.py, line 53 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdDFes4dbRh8GLZrNf:-MUdDFet5d0PS4H7jG_S:bcf9w45) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L53)):*
> ```
> error_tracker = False
> ```
This might be clearer as `error_detected`
Could be misunderstood as meaning we are not tracking errors as is.
Plus later your condition becomes `if error_detected:`
___
*[ops/check.py, line 106 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdEehfEwToSKgdXG5-:-MUdEehfEwToSKgdXG50:b-ubpnrm) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L106)):*
> ```
>             f"Checking against panelapp dump from {', '.join(files.values())} "
>             f"against database on {get_date()}: correct"
> ```
first `against` not needed

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[ops/check.py, line 15 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdGZeo9JroCzkR67iP:-MUhEUeM0prqbKecOSpx:b-ftvwyc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ci2targets
> ```
Are the targets the panels associated with each indication?
</blockquote></details>

yes, do you want to change the name of the variable? (it's a remnant of the old code when i thought clinical indications with single genes wouldn't be panels)
___
*[ops/check.py, line 53 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdDFes4dbRh8GLZrNf:-MUhVMWK4oLxjbGxg6bY:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L53)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> error_tracker = False
> ```
This might be clearer as `error_detected`
Could be misunderstood as meaning we are not tracking errors as is.
Plus later your condition becomes `if error_detected:`
</blockquote></details>

Done.
___
*[ops/check.py, line 106 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdEehfEwToSKgdXG5-:-MUhVLzS9HkZCnfdcgR9:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L106)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>             f"Checking against panelapp dump from {', '.join(files.values())} "
>             f"against database on {get_date()}: correct"
> ```
first `against` not needed
</blockquote></details>

Done.
___
*[ops/check.py, line 370 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MT7-ouDAaANPDF-pqOZ:-MUhVKnh1kUqm3ZP8Jvr:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L370)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: all files reviewed, 5 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/check.py, line 15 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/26#-MUdGZeo9JroCzkR67iP:-MUjhVH07pDtHjtPbNVp:b-e7atzv) ([raw file](https://github.com/eastgenomics/panel_ops/blob/17d190dbb4f1be0fe27277b243131df64e8d3008/ops/check.py#L15)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

yes, do you want to change the name of the variable? (it's a remnant of the old code when i thought clinical indications with single genes wouldn't be panels)
</blockquote></details>

Ideally, but it's not essential, particularly if it will require you to modify other PRs (i.e. calls of this function) to keep this consistent. 
I'll leave this to your judgement.

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: all files reviewed, 4 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
