### PR TITLE
V1.0.0 main

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[main.py, line 121 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT72ttI3shg2jn70RQK:-MT72ttI3shg2jn70RQL:bi27euj) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L121)):*
> ```Python
>             # Primary keys for importing the data in the database
>             pk_dict = {
>                 # they start at 1 because I loop over those elements
> ```

they start at 0?
___
*[main.py, line 174 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT738R6EcClkLDneFzJ:-MT738R6EcClkLDneFzK:b-ugc3jf) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L174)):*
> ```Python
> 
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser(
> ```

a separate args function is nicer when there's lots
___
*[main.py, line 231 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT73MzS-wOuNBtPyM8Q:-MT73MzS-wOuNBtPyM8R:bs0zpz5) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L231)):*
> ```Python
>     mod_db.add_argument(
>         "-i", "--initial_import",
>         help="Import pointed json in the database"
> ```

pointed json?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[main.py, line 121 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT72ttI3shg2jn70RQK:-MTAYnkCD3HUTKngduvy:b-g8q24c) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L121)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

they start at 0?
</blockquote></details>

easier to control the increment i.e. when i create a panel obj, i increment +1 just before
___
*[main.py, line 174 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT738R6EcClkLDneFzJ:-MTAZ2dRB0Q2nCJhOL3B:b-bv771k) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L174)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

a separate args function is nicer when there's lots
</blockquote></details>

separate function for each subparser?
___
*[main.py, line 231 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT73MzS-wOuNBtPyM8Q:-MTAZ5Zl9-rJ8xNzvPvi:b-n86f68) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L231)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

pointed json?
</blockquote></details>

poorly worded indeed

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[main.py, line 174 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MT738R6EcClkLDneFzJ:-MU8Olw07JQHDtVKT3DQ:b-ww58ar) ([raw file](https://github.com/eastgenomics/panel_ops/blob/40a7632f37538cabd9b36a38d40bac0179068102/main.py#L174)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

separate function for each subparser?
</blockquote></details>

nah just one, I like having a `def  parse_args()` or something to store them all in to keep it cleaner

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: all files reviewed, 6 unresolved discussions (waiting on @Yu-jinKim)

___
*[main.py, line 9 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUK5Gqn8Jf7CoYtbZwv:-MUK5GqoBMdfcRM4f14O:b-56rkc3) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L9)):*
> ```
> using only all panels
> ```
using all panels
___
*[main.py, line 43 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUK6Its3KXiDdcnEn4x:-MUK6Its3KXiDdcnEn4y:by1nhek) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L43)):*
> ```
> if param["command"] == "check":
> ```
Could we add a comment to describe the purpose of the following block?
___
*[main.py, line 121 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKBUvWBR4nQOHPm121:-MUKBUvWBR4nQOHPm122:bz422ot) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L121)):*
> ```
>                 # they start at 1 because I loop over those elements
>                 # makes it easier to keep track off
> ```
Looks like they start at 0 in the dict
___
*[main.py, line 123 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKBfeq0zujT5Ita5lO:-MUKBfeq0zujT5Ita5lP:brj0bpa) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L123)):*
> ```
> + might that in the update process later
> ```
Not sure that I understand this
___
*[main.py, line 133 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKBq0eCZIfrtXrwS2k:-MUKBq0eCZIfrtXrwS2l:bbyojs9) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L133)):*
> ```
>             ) = ops.utils.parse_hgnc_dump(files["hgnc"])
>             # get all transcripts in nirvana gff
> ```
Newline to separate these could make it a little clearer
___
*[main.py, line 235 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKCQ7fEd7wNOxXSaYP:-MUKCQ7gCdnooalL7ptO:b-a9790d) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L235)):*
<details><summary><i alt="summary">Quoted 61 lines of code…</i></summary>

> ```
>     parser = argparse.ArgumentParser(
>         description="Prepare and import data for Panelapp database"
>     )
>     parser.add_argument("-t", "--test_xls", help="NHS test directory")
>     subparser = parser.add_subparsers(dest="command")
>     generate = subparser.add_parser("generate")
>     generate.add_argument(
>         "-gms", "--panelapp_gms", action="store_true",
>         help="Generate panelapp GMS dump"
>     )
>     generate.add_argument(
>         "-non-gms", "--panelapp_non_gms", action="store_true",
>         help="Generate panelapp non-GMS dump"
>     )
>     generate.add_argument(
>         "-all", "--panelapp_all", action="store_true",
>         help="Generate all panelapp dump"
>     )
>     generate.add_argument(
>         "-j", "--json", metavar="KEY=VALUE", nargs=4,
>         help=(
>             "Generate django json that need to be imported in the database. "
>             "Generating the jsons files require 4 files: "
>             "the panelapp dump(s)/custom dump(s) to actually import, "
>             "genes2transcripts file, hgnc dump and the nirvana GFF. They need "
>             "to be given as following: panels=folder,folder hgnc=file "
>             "g2t=file nirvana=file. The panelapp dump file path should "
>             "contain the following string: gms, non-gms, in-house, "
>             "single_gene. This allows to find the type of panel the folder "
>             "contains."
>         )
>     )
>     generate.add_argument(
>         "-gp", "--genepanels", action="store_true",
>         help="Generate genepanels"
>     )
>     generate.add_argument("-m", "--manifest", help="Gemini database xls dump")
>     check = subparser.add_parser("check")
>     check.add_argument(
>         "dumps", metavar="KEY=VALUE", nargs=4,
>         help=(
>             "Provide panelapp dump and genes2transcripts. The format for "
>             "passing those arguments is: panels=folder,folder hgnc=file g2t=file "
>             "nirvana=file."
>         )
>     )
>     mod_db = subparser.add_parser("mod_db")
>     mod_db.add_argument("user", help="Admin username for panel_database")
>     mod_db.add_argument("passwd", help="Admin passwd for panel_database")
>     mod_db.add_argument(
>         "-i", "--initial_import",
>         help="Import given json in the database"
>     )
>     mod_db.add_argument(
>         "-hgnc", "--hgnc", metavar="KEY=VALUE", nargs=4,
>         help=(
>             "Import hgnc dump in the database. Need to provide "
>             "hgnc=file date=yymmdd nirvana=file g2t=file"
>         )
>     )
>     args = vars(parser.parse_args())
> ```
</details>

A separate function to contain all this would be tidier

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: all files reviewed, 7 unresolved discussions (waiting on @Yu-jinKim)

___
*[main.py, line 80 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKFGuu75LCRNR5dyho:-MUKFGuu75LCRNR5dyhp:b-l43epw) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L80)):*
> ```
> if param["panelapp_all"] is True:
> ```
`if param["panelapp_all"]:` would be more pythonic

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[main.py, line 123 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKBfeq0zujT5Ita5lO:-MUO3_1980H071a1I90V:b3yp70f) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L123)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> + might that in the update process later
> ```
Not sure that I understand this
</blockquote></details>

the idea i had in mind was to use this dict for the updating process i.e. get the latest key that was created for each element and start from this key.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[main.py, line 235 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKCQ7fEd7wNOxXSaYP:-MUO7X4vCCbr_GTThs6L:bhsnd9q) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L235)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     parser = argparse.ArgumentParser(
>         description="Prepare and import data for Panelapp database"
>     )
>     parser.add_argument("-t", "--test_xls", help="NHS test directory")
>     subparser = parser.add_subparsers(dest="command")
>     generate = subparser.add_parser("generate")
>     generate.add_argument(
>         "-gms", "--panelapp_gms", action="store_true",
>         help="Generate panelapp GMS dump"
>     )
>     generate.add_argument(
>         "-non-gms", "--panelapp_non_gms", action="store_true",
>         help="Generate panelapp non-GMS dump"
>     )
>     generate.add_argument(
>         "-all", "--panelapp_all", action="store_true",
>         help="Generate all panelapp dump"
>     )
>     generate.add_argument(
>         "-j", "--json", metavar="KEY=VALUE", nargs=4,
>         help=(
>             "Generate django json that need to be imported in the database. "
>             "Generating the jsons files require 4 files: "
>             "the panelapp dump(s)/custom dump(s) to actually import, "
>             "genes2transcripts file, hgnc dump and the nirvana GFF. They need "
>             "to be given as following: panels=folder,folder hgnc=file "
>             "g2t=file nirvana=file. The panelapp dump file path should "
>             "contain the following string: gms, non-gms, in-house, "
>             "single_gene. This allows to find the type of panel the folder "
>             "contains."
>         )
>     )
>     generate.add_argument(
>         "-gp", "--genepanels", action="store_true",
>         help="Generate genepanels"
>     )
>     generate.add_argument("-m", "--manifest", help="Gemini database xls dump")
>     check = subparser.add_parser("check")
>     check.add_argument(
>         "dumps", metavar="KEY=VALUE", nargs=4,
>         help=(
>             "Provide panelapp dump and genes2transcripts. The format for "
>             "passing those arguments is: panels=folder,folder hgnc=file g2t=file "
>             "nirvana=file."
>         )
>     )
>     mod_db = subparser.add_parser("mod_db")
>     mod_db.add_argument("user", help="Admin username for panel_database")
>     mod_db.add_argument("passwd", help="Admin passwd for panel_database")
>     mod_db.add_argument(
>         "-i", "--initial_import",
>         help="Import given json in the database"
>     )
>     mod_db.add_argument(
>         "-hgnc", "--hgnc", metavar="KEY=VALUE", nargs=4,
>         help=(
>             "Import hgnc dump in the database. Need to provide "
>             "hgnc=file date=yymmdd nirvana=file g2t=file"
>         )
>     )
>     args = vars(parser.parse_args())
> ```
A separate function to contain all this would be tidier
</blockquote></details>

i had a talk with jethro about it. I don't think it'd be tidier unless i create functions for each subparser. If i write a function for the whole argparse bit i'd be copy pasting every thing as is

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[main.py, line 9 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUK5Gqn8Jf7CoYtbZwv:-MUOA5H8AxzJIvF0CvQc:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L9)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> using only all panels
> ```
using all panels
</blockquote></details>

Done.
___
*[main.py, line 43 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUK6Its3KXiDdcnEn4x:-MUOA5tU-IG9X1samj3i:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> if param["command"] == "check":
> ```
Could we add a comment to describe the purpose of the following block?
</blockquote></details>

Done.
___
*[main.py, line 80 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKFGuu75LCRNR5dyho:-MUOAT0224nyeOCZq8rh:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L80)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> if param["panelapp_all"] is True:
> ```
`if param["panelapp_all"]:` would be more pythonic
</blockquote></details>

Done.
___
*[main.py, line 121 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKBUvWBR4nQOHPm121:-MUOATsP3WKrmfvpTrtG:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L121)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>                 # they start at 1 because I loop over those elements
>                 # makes it easier to keep track off
> ```
Looks like they start at 0 in the dict
</blockquote></details>

Done.
___
*[main.py, line 133 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKBq0eCZIfrtXrwS2k:-MUOAUrZ9eymEdKPbGB9:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L133)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>             ) = ops.utils.parse_hgnc_dump(files["hgnc"])
>             # get all transcripts in nirvana gff
> ```
Newline to separate these could make it a little clearer
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[main.py, line 235 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKCQ7fEd7wNOxXSaYP:-MUOinKl1BIGBFq7uz5-:bwhv3s1) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L235)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i had a talk with jethro about it. I don't think it'd be tidier unless i create functions for each subparser. If i write a function for the whole argparse bit i'd be copy pasting every thing as is
</blockquote></details>

I agree with Matt, I think it's cleaner to just put it all in one function and separate the argument parsing from the main logic

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[main.py, line 235 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKCQ7fEd7wNOxXSaYP:-MUSj4RW5lkNFXNB0qm5:bmjddmq) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L235)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I agree with Matt, I think it's cleaner to just put it all in one function and separate the argument parsing from the main logic
</blockquote></details>

Still not convinced but done

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[main.py, line 235 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/23#-MUKCQ7fEd7wNOxXSaYP:-MUSjEShBRz7t6uqBxKd:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/be9ac164c6f29d10ad2dfebe5ce7147d9a1fc2ff/main.py#L235)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Still not convinced but done
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
