### PR TITLE
V1.0.0 mod db

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/mod_db.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/25#-MShPVbzByTgxvUIo3aD:-MShPVbzByTgxvUIo3aE:bakl68y) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ced5fef9f26ae67ba1c89f1db8cfe1fc694cc629/ops/mod_db.py#L92)):*
> ```Python
>             # So there's this method called bulk_create() and I tried using
>             # that but I kept getting this following error
>             # django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
> ```

MySQL has had enough of you....
Have you checked on what packet size limit and timeout you have set for the database? Might need increasing to take one big query

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[ops/mod_db.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/25#-MShPVbzByTgxvUIo3aD:-MTA_68iCoOoRq2yCueO:blrtn13) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ced5fef9f26ae67ba1c89f1db8cfe1fc694cc629/ops/mod_db.py#L92)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

MySQL has had enough of you....
Have you checked on what packet size limit and timeout you have set for the database? Might need increasing to take one big query
</blockquote></details>

not sure if i want tweak even more things for the db

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[ops/mod_db.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/25#-MShPVbzByTgxvUIo3aD:-MUh84tADg6Qar8gKz1d:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ced5fef9f26ae67ba1c89f1db8cfe1fc694cc629/ops/mod_db.py#L92)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not sure if i want tweak even more things for the db
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/25#-:-MUm9mTN5Ib8KwtsohlB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
